### ISSUE TITLE
Problem with cli

### ISSUE THREAD

**Issue by garethnellis** [robjhyndman/cricketdata#33]
When I load the package and run `IndiaODIBowling <- fetch_cricinfo("ODI", "men", "bowling", country = "india")` I get the error: `Error in cli::cli_progress_update() : Cannot find current progress bar for `<environment: 0x000001e793f2afc0>``

**Comment by robjhyndman** [comment]
It should be fixed in https://github.com/robjhyndman/cricketdata/commit/dedb9d26a05accda745415935263d0f57c141a2b.

**Comment by neilfws** [comment]
I am still seeing this error, although I've installed the latest cricketdata from Github (version 0.2.3, Mac OS X, R version 4.3.2).
